##Simple service to expose application on port 30081
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: argo-repo-test
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081   
  type: NodePort
